name: CI/CD Push to Dockerhub and Huggingface Spaces

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t joshiacahyadi/diabetes_classifier:latest .

      - name: Push Docker image
        run: docker push joshiacahyadi/diabetes_classifier:latest

      - name: Install huggingface-cli
        run: pip install -U "huggingface_hub[cli]"

      - name: Login to Huggingface
        run: huggingface-cli login --token ${{ secrets.HUGGINGFACE_TOKEN }}

      - name: Deploy to the Huggingface Spaces
        run: huggingface-cli push --image joshiacahyadi/diabetes_classifier:latest --push-to-production --name diabetes_classifier_webapp
