name: CI/CD Push to Dockerhub and Huggingface Spaces

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t joshiacahyadi/diabetes_classifier:latest .

      - name: Push Docker image to dockerhub
        run: docker push joshiacahyadi/diabetes_classifier:latest

      - name: Install huggingface-cli
        run: pip install -U "huggingface_hub[cli]"

      - name: Push to Huggingface Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://joocahyadi:$HF_TOKEN@huggingface.co/spaces/joocahyadi/diabetes_classifier_webapp main
